/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6-dev */

#include "blockchain.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(BlockHeader, BlockHeader, 2)


PB_BIND(BlockHeaderCore, BlockHeaderCore, 2)


PB_BIND(EpochData, EpochData, AUTO)


PB_BIND(ChainMeta, ChainMeta, AUTO)


PB_BIND(BlockMeta, BlockMeta, 2)


PB_BIND(BlockIdentifier, BlockIdentifier, AUTO)


PB_BIND(AccountMeta, AccountMeta, AUTO)



