#ifndef IOTEX_CONSTANTS_H
#define IOTEX_CONSTANTS_H

// TODO Move these to a namespace instead of preprocessor macros

#define IOTEX_HASH_SIZE 32
#define IOTEX_PRIVATE_KEY_SIZE 32
#define IOTEX_PUBLIC_KEY_SIZE 65
#define IOTEX_SIGNATURE_SIZE 65

#define IOTEX_ADDRESS_STRLEN    42
#define IOTEX_MAX_BALANCE_STRLEN    30
#define ETH_ADDRESS_STRLEN  43
#define IOTEX_HASH_STRLEN    (IOTEX_HASH_SIZE * 2)
#define IOTEX_PUBLIC_KEY_STRLEN    (IOTEX_PUBLIC_KEY_SIZE * 2)
#define IOTEX_PRIVATE_KEY_STRLEN    (IOTEX_PRIVATE_KEY_SIZE * 2)
#define IOTEX_SIGNATURE_STRLEN    (IOTEX_SIGNATURE_SIZE * 2)
#define IOTEX_TIMESTAMP_STRLEN    21 // TODO check if this is correct or it can be bigger

#endif
